apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cluster1-829c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cluster1-829c"
  template:
    metadata:
      labels:
        app: "cluster1-829c"
    spec:
      containers:
        - name: "cluster1-829c"
          image: "githubactioncontaineracr.azurecr.io/cluster1"
          ports:
          - containerPort: 80